### ISSUE TITLE
Site appears to be down

### ISSUE THREAD

**Issue by Mindful** [Wilfred/simpla-vortaro#16]
(I apologize if someone else was hosting the website at http://www.simplavortaro.org/ - in that case, please feel free to just close the issue)

I was just sitting down to implement something using simpla vortaro's API when I noticed the site was down. That was a couple days ago, and it looks like it's still down. Should I plan on it coming back at some point, or are there no further plans to keep it hosted somewhere?

**Comment by Wilfred** [comment]
Ve! Ĝi ja funkciu!

It's on a Digital Ocean server. Thanks for letting me know, I really thought I had monitoring but clearly not enough.

**Comment by Wilfred** [comment]
Should be sorted now (disk had filled up), and I've fixed the monitoring.

Let me know if you see any issue.

(Kaj koran dankon por informi min :) )
